Protein Function Prediction Mode...
in total: 8420 proteins
encoding protein...
unique target sequence: 8383
Done.
Protein Function Prediction Mode...
in total: 2811 proteins
encoding protein...
unique target sequence: 2807
Done.
Protein Function Prediction Mode...
in total: 2773 proteins
encoding protein...
unique target sequence: 2768
Done.
Let's use 1 GPU!
--- Data Preparation ---
--- Go for Training ---
E:\anaconda3\envs\graph\lib\site-packages\torch\autograd\graph.py:744: UserWarning: Plan failed with a cudnnException: CUDNN_BACKEND_EXECUTION_PLAN_DESCRIPTOR: cudnnFinalize Descriptor Failed cudnn_status: CUDNN_STATUS_NOT_SUPPORTED (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\cudnn\Conv_v8.cpp:919.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Training at Epoch 1 iteration 0 with loss 2.30178. Total time 0.00888 hours
Training at Epoch 1 iteration 100 with loss 2.20278. Total time 0.01027 hours
Training at Epoch 1 iteration 200 with loss 2.25098. Total time 0.01138 hours
Traceback (most recent call last):
  File "E:\DeepPurposePlusPlus\train\subcellular.py", line 88, in <module>
    model.train(train, val, test, compute_pos_enc = compute_pos)
  File "E:\DeepPurposePlusPlus\ProB\ProteinPred.py", line 460, in train
    table.add_row(lst)
  File "E:\anaconda3\envs\graph\lib\site-packages\prettytable\prettytable.py", line 1415, in add_row
    raise ValueError(msg)
ValueError: Row has incorrect number of values, (actual) 4!=3 (expected)
Validation at Epoch 1 , Accuracy: 0.28779 , AUPRC: 0.15441 , F1: 0.04469