2024-07-17 18:50:18,096 INFO    StreamThr :212082 [internal.py:wandb_internal():85] W&B internal server running at pid: 212082, started at: 2024-07-17 18:50:18.095658
2024-07-17 18:50:18,097 DEBUG   HandlerThread:212082 [handler.py:handle_request():158] handle_request: status
2024-07-17 18:50:18,099 INFO    WriterThread:212082 [datastore.py:open_for_write():87] open: /home/jiaqing/Desktop/DeepPurposePlusPlus/wandb/run-20240717_185018-1zxot6w5/run-1zxot6w5.wandb
2024-07-17 18:50:18,100 DEBUG   SenderThread:212082 [sender.py:send():379] send: header
2024-07-17 18:50:18,136 DEBUG   SenderThread:212082 [sender.py:send():379] send: run
2024-07-17 18:50:18,792 ERROR   SenderThread:212082 [internal_api.py:execute():349] 500 response executing GraphQL.
2024-07-17 18:50:18,792 ERROR   SenderThread:212082 [internal_api.py:execute():350] {"error":"An internal error occurred. Please contact support."}
2024-07-17 18:50:20,071 ERROR   SenderThread:212082 [internal_api.py:execute():349] 500 response executing GraphQL.
2024-07-17 18:50:20,072 ERROR   SenderThread:212082 [internal_api.py:execute():350] {"error":"An internal error occurred. Please contact support."}
2024-07-17 18:50:22,791 ERROR   SenderThread:212082 [internal_api.py:execute():349] 500 response executing GraphQL.
2024-07-17 18:50:22,791 ERROR   SenderThread:212082 [internal_api.py:execute():350] {"error":"An internal error occurred. Please contact support."}
2024-07-17 18:50:22,791 INFO    SenderThread:212082 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/home/jiaqing/miniconda3/envs/graph/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/home/jiaqing/miniconda3/envs/graph/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 345, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/home/jiaqing/miniconda3/envs/graph/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/home/jiaqing/miniconda3/envs/graph/lib/python3.9/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/home/jiaqing/miniconda3/envs/graph/lib/python3.9/site-packages/wandb/sdk/lib/gql_request.py", line 59, in execute
    request.raise_for_status()
  File "/home/jiaqing/miniconda3/envs/graph/lib/python3.9/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://api.wandb.ai/graphql
2024-07-17 18:50:23,137 DEBUG   HandlerThread:212082 [handler.py:handle_request():158] handle_request: keepalive
2024-07-17 18:50:27,535 ERROR   SenderThread:212082 [internal_api.py:execute():349] 500 response executing GraphQL.
2024-07-17 18:50:27,535 ERROR   SenderThread:212082 [internal_api.py:execute():350] {"error":"An internal error occurred. Please contact support."}
2024-07-17 18:50:28,139 DEBUG   HandlerThread:212082 [handler.py:handle_request():158] handle_request: keepalive
2024-07-17 18:50:33,140 DEBUG   HandlerThread:212082 [handler.py:handle_request():158] handle_request: keepalive
2024-07-17 18:50:36,118 ERROR   SenderThread:212082 [internal_api.py:execute():349] 500 response executing GraphQL.
2024-07-17 18:50:36,118 ERROR   SenderThread:212082 [internal_api.py:execute():350] {"error":"An internal error occurred. Please contact support."}
2024-07-17 18:50:38,142 DEBUG   HandlerThread:212082 [handler.py:handle_request():158] handle_request: keepalive
2024-07-17 18:50:43,143 DEBUG   HandlerThread:212082 [handler.py:handle_request():158] handle_request: keepalive
2024-07-17 18:50:48,144 DEBUG   HandlerThread:212082 [handler.py:handle_request():158] handle_request: keepalive
2024-07-17 18:50:53,146 DEBUG   HandlerThread:212082 [handler.py:handle_request():158] handle_request: keepalive
2024-07-17 18:50:55,130 ERROR   SenderThread:212082 [internal_api.py:execute():349] 500 response executing GraphQL.
2024-07-17 18:50:55,130 ERROR   SenderThread:212082 [internal_api.py:execute():350] {"error":"An internal error occurred. Please contact support."}
2024-07-17 18:50:58,147 DEBUG   HandlerThread:212082 [handler.py:handle_request():158] handle_request: keepalive
2024-07-17 18:51:03,148 DEBUG   HandlerThread:212082 [handler.py:handle_request():158] handle_request: keepalive
2024-07-17 18:51:08,150 DEBUG   HandlerThread:212082 [handler.py:handle_request():158] handle_request: keepalive
2024-07-17 18:51:12,084 DEBUG   HandlerThread:212082 [handler.py:handle_request():158] handle_request: shutdown
2024-07-17 18:51:12,084 INFO    HandlerThread:212082 [handler.py:finish():882] shutting down handler
2024-07-17 18:51:12,143 INFO    WriterThread:212082 [datastore.py:close():296] close: /home/jiaqing/Desktop/DeepPurposePlusPlus/wandb/run-20240717_185018-1zxot6w5/run-1zxot6w5.wandb
2024-07-17 18:51:33,864 ERROR   SenderThread:212082 [internal_api.py:execute():349] 500 response executing GraphQL.
2024-07-17 18:51:33,864 ERROR   SenderThread:212082 [internal_api.py:execute():350] {"error":"An internal error occurred. Please contact support."}
2024-07-17 18:52:40,678 ERROR   SenderThread:212082 [internal_api.py:execute():349] 500 response executing GraphQL.
2024-07-17 18:52:40,678 ERROR   SenderThread:212082 [internal_api.py:execute():350] {"error":"An internal error occurred. Please contact support."}
2024-07-17 19:00:00,820 INFO    SenderThread:212082 [dir_watcher.py:__init__():211] watching files in: /home/jiaqing/Desktop/DeepPurposePlusPlus/wandb/run-20240717_185018-1zxot6w5/files
2024-07-17 19:00:00,820 INFO    SenderThread:212082 [sender.py:_start_run_threads():1188] run started: 1zxot6w5 with start time 1721213418.095429
2024-07-17 19:00:00,820 INFO    SenderThread:212082 [sender.py:finish():1608] shutting down sender
2024-07-17 19:00:00,820 INFO    SenderThread:212082 [dir_watcher.py:finish():358] shutting down directory watcher
2024-07-17 19:00:01,821 INFO    SenderThread:212082 [dir_watcher.py:finish():388] scan: /home/jiaqing/Desktop/DeepPurposePlusPlus/wandb/run-20240717_185018-1zxot6w5/files
2024-07-17 19:00:01,821 INFO    SenderThread:212082 [dir_watcher.py:finish():402] scan save: /home/jiaqing/Desktop/DeepPurposePlusPlus/wandb/run-20240717_185018-1zxot6w5/files/config.yaml config.yaml
2024-07-17 19:00:01,821 INFO    SenderThread:212082 [file_pusher.py:finish():169] shutting down file pusher
2024-07-17 19:00:01,821 INFO    SenderThread:212082 [file_pusher.py:join():175] waiting for file pusher
2024-07-17 19:00:03,565 INFO    wandb-upload_0:212082 [upload_job.py:push():130] Uploaded file /home/jiaqing/Desktop/DeepPurposePlusPlus/wandb/run-20240717_185018-1zxot6w5/files/config.yaml
2024-07-17 19:00:03,824 INFO    SenderThread:212082 [file_stream.py:finish():601] file stream finish called
2024-07-17 19:00:04,777 INFO    SenderThread:212082 [file_stream.py:finish():605] file stream finish is done
